config/routes.rb
Rails.application.routes.draw do
  root 'countries#index'
  resources :countries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state

  # Column name is required
  validates :name, presence: true

  before_validation  :upercase_fields

  def upercase_fields
    if !self.name.nil?
      self.name.upcase!
    end
  end
end

app/models/country.rb
class Country < ApplicationRecord

  has_many :states, dependent: :destroy

  accepts_nested_attributes_for :states,
    reject_if: proc { |attr| attr['name'].blank? },
    allow_destroy: true

  # Column name is required
  validates :name, presence: true

  # Name always in upper case
  before_save :name_upcase

  def name_upcase
    self.name.upcase!
  end
end

app/models/state.rb
class State < ApplicationRecord

  belongs_to :country
  has_many :cities, dependent: :destroy

  accepts_nested_attributes_for :cities,
    reject_if: proc { |attr| attr['name'].blank? },
    allow_destroy: true

  # Column name is required
  validates :name, presence: true

  before_validation  :upercase_fields

  def upercase_fields
    if !self.name.nil?
      self.name.upcase!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]
  before_action :set_build, only: [ :edit]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
    set_build
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        set_build
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      # Permit parameters of state, and the action destroy
      params.require(:country).permit(:name, states_attributes: [:id, :name, :_destroy, cities_attributes: [:id, :name, :_destroy] ])
    end

    def set_build
      @country.states.build.cities.build # Permit create States and Cities
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.erb
<%= form_with(model: country, local: true) do |form| %>
  <% if country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <h2 class="">States</h2><h4>and cities</h4>
  <ul class="list-group">
    <%= form.fields_for :states do |state| %>
        <li class="list-group-item">
          <%= state.text_field :name ,placeholder: 'state name'%>
          <% if !state.object.id.nil? %>
            <%= state.check_box :_destroy %> <span class="font-size-smaller "> (check to delete) </span>
          <% end %>

          <ul class="list-group">
            <%= state.fields_for :cities do |city| %>
              <li class="list-group-item">
                <%= city.text_field :name ,placeholder: 'city name'%>
                <% if !city.object.id.nil? %>
                  <%= city.check_box :_destroy %> <span class="font-size-smaller "> (check to delete) </span>
                <% end %>
              </li>
            <% end %>

            <% if !state.object.id.nil? %>
              <%= state.fields_for :cities, City.new do |city| %>
                <li class="list-group-item">
                  <%= city.text_field :name , placeholder: "city name"%>
                </li>
              <% end %>
            <% end %>
          </ul>

        </li>
    <% end %>
  </ul>
  <hr class="invisible">
  <div class="row">
    <div class="col col-xl-3 col-lg-3 col-md-6">
      <%= form.submit 'Save', class: 'btn btn-success btn-block'%>
    </div>
  </div>

<% end %>

app/views/countries/edit.html.erb
<div class="container">
  <h1>Editing Country</h1>

  <div class="row">
    <div class="col">
      <%= render 'form', country: @country %>
    </div>
  </div>
  <hr class="invisible">
  <div class="row">
    <div class="col col-xl-3 col-lg-3 col-md-6">
      <%= link_to 'Back', countries_path, class: 'btn btn-secondary btn-block' %>
    </div>
  </div>

</div>

app/views/countries/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Countries</h1>
    <ul class="list-group">
      <% @countries.each do |country| %>
        <li class="list-group-item">
          <%= link_to country.name, edit_country_path(country) %>
          <div class="d-flex justify-content-end">
            <%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>

        </li>
      <% end %>
    </ul>
  <br>
  <%= link_to 'New Country', new_country_path, class: 'btn btn-primary' %>
</div>

app/views/countries/new.html.erb
<div class="container">

  <h1>New Country</h1>


  <div class="row">
    <div class="col">
      <%= render 'form', country: @country %>
    </div>
  </div>
  <hr class="invisible">
  <div class="row">
    <div class="col col-xl-3 col-lg-3 col-md-6">
      <%= link_to 'Back', countries_path, class: 'btn btn-secondary btn-block' %>
    </div>
  </div>


</div>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @country.name %>
</p>

<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NestedForms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>